# Generated by Django 3.0.8 on 2020-08-09 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attach_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
