# Generated by Django 3.0.8 on 2020-08-09 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200809_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='attach_photo',
            field=models.ImageField(blank=True, null=True, upload_to='posts'),
        ),
    ]
